### ISSUE TITLE
开mod进游戏直接红字

### ISSUE THREAD

**Issue by SagiZJS** [xyzkljl1/Taiwu_EffectInfo#1]
只额外开了加背包负重的

```
Mono path[0] = 'F:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/The Scroll of Taiwu_Data/Managed'
Mono config path = 'F:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/MonoBleedingEdge/etc'
PlayerConnection initialized from F:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/The Scroll of Taiwu_Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55048
Multi-casting "[IP] 192.168.86.84 [Port] 55048 [Flags] 2 [Guid] 507420845 [EditorId] 1431679527 [Version] 1048832 [Id] WindowsPlayer(DESKTOP-EQ0UIAV) [Debug] 0 [PackageName] WindowsPlayer" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55048]
PlayerConnection already initialized - listening to [0.0.0.0:55048]
Initialize engine version: 2018.4.23f1 (c9cf1a90e812)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 3080 Ti (ID=0x2208)
    Vendor:   
    VRAM:     12108 MB
    Driver:   31.0.15.1694
Begin MonoManager ReloadAssembly
- Completed reload, in  0.113 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.438300 ms
Game start at 2022/10/5 18:58:56
Game version = V0.0.25.1
[]Awake Singleton.
Setting breakpad minidump AppID = 838350
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198157156800 [API loaded no]
Verifying steam user successful! steam id 76561198157156800
Unloading 5 Unused Serialized files (Serialized files now loaded: 178)
System memory in use before: 200.2 MB.
System memory in use after: 200.5 MB.

Unloading 133 unused Assets to reduce memory usage. Loaded Objects now: 4301.
Total: 32.191300 ms (FindLiveObjects: 0.420600 ms CreateObjectMapping: 0.147900 ms MarkObjects: 31.547000 ms  DeleteObjects: 0.075200 ms)

Total 5 local mods found.
Start loading mod punkc生活质量mod for frontend ...
 - Loading plugin from Frontend.dll
Fallback handler could not load library F:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/The Scroll of Taiwu_Data/Mono/data-0000024E7E9DBDF0.dll
Fallback handler could not load library F:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/The Scroll of Taiwu_Data/Mono/data-0000024E13024170.dll
Start loading mod 快速战斗 for frontend ...
 - Loading plugin from QuickFightForeEnd.dll
Fallback handler could not load library F:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/The Scroll of Taiwu_Data/Mono/data-0000024E1274DA50.dll
Start loading mod ~更多信息 v0.8~ for frontend ...
 - Loading plugin from MynahBaseModBase.dll
Fallback handler could not load library F:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/The Scroll of Taiwu_Data/Mono/data-0000024E2282CDE0.dll
 - Loading plugin from MynahBaseModFrontend.dll
Fallback handler could not load library F:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/The Scroll of Taiwu_Data/Mono/data-0000024E10F288A0.dll
 - Loading plugin from MynahMoreInfo.dll
Fallback handler could not load library F:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/The Scroll of Taiwu_Data/Mono/data-0000024E775E8950.dll
ShowSpecialEffect all patched
Start loading mod 洞察 for frontend ...
 - Loading plugin from EffectInfoFrontend.dll
Fallback handler could not load library F:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/The Scroll of Taiwu_Data/Mono/data-0000024E12DFC030.dll
Fallback handler could not load library F:/SteamLibrary/steamapps/common/The Scroll Of Taiwu/The Scroll of Taiwu_Data/Mono/data-0000024E779D1F30.dll
Total 4 mods loaded into the game.
ReadInterProcessMessages thread started.
WriteInterProcessMessages thread started.
Outgoing message: Initialize
Incoming message: GameModuleInitialized
Total 5 local mods found.
Start unloading mod 洞察 for frontend ...
 - Unloading plugin EffectInfo
Start unloading mod ~更多信息 v0.8~ for frontend ...
 - Unloading plugin MynahMoreInfo
 - Unloading plugin MynahBaseModFrontend
 - Unloading plugin MynahBaseModBase
Start unloading mod 快速战斗 for frontend ...
 - Unloading plugin 快速战斗
Start unloading mod punkc生活质量mod for frontend ...
 - Unloading plugin QualityOfLife
Start loading mod punkc生活质量mod for frontend ...
 - Loading plugin from Frontend.dll
Start loading mod 洞察 for frontend ...
 - Loading plugin from EffectInfoFrontend.dll
Total 2 mods loaded into the game.
Outgoing message: Initialize
Incoming message: GameModuleInitialized
Unloading 1 Unused Serialized files (Serialized files now loaded: 188)
System memory in use before: 0.57 GB.
System memory in use after: 0.59 GB.

Unloading 153664 unused Assets to reduce memory usage. Loaded Objects now: 171687.
Total: 260.109700 ms (FindLiveObjects: 12.291700 ms CreateObjectMapping: 7.345200 ms MarkObjects: 197.619800 ms  DeleteObjects: 42.852100 ms)

MainStoryLine progress notified:from 0 to 22
太吾ID：5515
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
BasicGameData:UpdateTaiwuDomainData(DataUid, Int32, RawDataPool)
BasicGameData:OnNotifyGameData(List`1)
GameData.GameDataBridge.GameDataBridge:ProcessNotifications()
GameData.GameDataBridge.UnityAdapter.GameDataBridgeUnityAdapter:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

同道隐藏状态：False
Incoming message: ErrorMessages
Incoming message: Disconnect
ReadInterProcessMessages thread is about to exit.
Outgoing message: Disconnect
WriteInterProcessMessages thread is about to exit.
2022-10-05 18:59:52.4383|ERROR|Main|GameData.Program|System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Int16 GameData.Domains.Character.AvatarSystem.AvatarData.GetCharm(Int16, Byte)'.
   at EffectInfo.EffectInfoBackend.GetAttractionInfo(CharacterDomain __instance, Character character)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at EffectInfo.EffectInfoBackend.GetCharacterDisplayDataPrePatch(CharacterDomain __instance, List`1 charIdList)
   at DMD<GameData.Domains.Character.CharacterDomain::GetCharacterDisplayDataList>(CharacterDomain this, List`1 charIdList)
   at GameData.Domains.Character.CharacterDomain.CallMethod(Operation operation, RawDataPool argDataPool, RawDataPool returnDataPool, DataContext context)
   at GameData.GameDataBridge.GameDataBridge.ProcessMethodCall(Operation operation, RawDataPool argDataPool, DataContext context)
   at GameData.GameDataBridge.GameDataBridge.ProcessOperations(DataContext context)
   at GameData.GameDataBridge.GameDataBridge.RunMainLoop()
   at GameData.Program.Main(String[] args)
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
GameData.GameDataBridge.GameDataBridge:CheckErrorMessages()
GameData.GameDataBridge.UnityAdapter.GameDataBridgeUnityAdapter:Update()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)


```

**Comment by xyzkljl1** [comment]
刚看到……
没想到会有人提issue,这个已经修了
